export const FETCH_COINS_REQUEST = "FETCH_COINS_REQUEST"
export const FETCH_COINS_SUCCESS = "FETCH_COINS_SUCCESS"
export const FETCH_COINS_FAILURE = "FETCH_COINS_FAILURE"

export const FETCH_TOP50_REQUEST = "FETCH_TOP50_REQUEST"
export const FETCH_TOP50_SUCCESS = "FETCH_TOP50_SUCCESS"
export const FETCH_TOP50_FAILURE = "FETCH_TOP50_FAILURE"

export const FETCH_COIN_DETAILS_BY_ID_REQUEST = "FETCH_COIN_DETAILS_BY_ID_REQUEST"
export const FETCH_COIN_DETAILS_BY_ID_SUCCESS = "FETCH_COIN_DETAILS_BY_ID_SUCCESS"
export const FETCH_COIN_DETAILS_BY_ID_FAILURE = "FETCH_COIN_DETAILS_BY_ID_FAILURE"

export const SEARCH_COIN_REQUEST = "SEARCH_COIN_REQUEST"
export const SEARCH_COIN_SUCCESS = "SEARCH_COIN_SUCCESS"
export const SEARCH_COIN_FAILURE = "SEARCH_COIN_FAILURE"

export const FETCH_COIN_MARKET_DATA_REQUEST = "FETCH_COIN_MARKET_DATA_REQUEST"
export const FETCH_COIN_MARKET_DATA_SUCCESS = "FETCH_COIN_MARKET_DATA_SUCCESS"
export const FETCH_COIN_MARKET_DATA_FAILURE = "FETCH_COIN_MARKET_DATA_FAILURE"


export const FETCH_COIN_DETAILS_REQUEST = "FETCH_COIN_DETAILS_REQUEST"
export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS"
export const FETCH_COIN_DETAILS_FAILURE = "FETCH_COIN_DETAILS_FAILURE"