export const GET_WALLET_REQUEST = 'GET_WALLET_REQUEST';
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_FAILURE = 'GET_WALLET_FAILURE';

export const GET_WALLET_TRANSACTIONS_REQUEST = 'GET_WALLET_TRANSACTIONS_REQUEST';
export const GET_WALLET_TRANSACTIONS_SUCCESS = 'GET_WALLET_TRANSACTIONS_SUCCESS';
export const GET_WALLET_TRANSACTIONS_FAILURE = 'GET_WALLET_TRANSACTIONS_FAILURE';

export const DEPOSIT_WALLET_REQUEST = 'DEPOSIT_WALLET_REQUEST'
export const DEPOSIT_WALLET_SUCCESS = 'DEPOSIT_WALLET_SUCCESS';
export const DEPOSIT_WALLET_FAILURE = 'DEPOSIT_WALLET_FAILURE';

export const TRANSFER_MONEY_REQUEST = 'TRANSFER_MONEY_REQUEST'
export const TRANSFER_MONEY_SUCCESS = 'TRANSFER_MONEY_SUCCESS';
export const TRANSFER_MONEY_FAILURE = 'TRANSFER_MONEY_FAILURE';

